version: '3.8'

services:
  carlasim:
    image: docetti/carla:0.9.13-1
    restart: "no"
    container_name: carlasim
    privileged: true
    ports:
      - "2000-2002:2000-2002"
    volumes:
      - './NoEditorSim/DefaultEngine.ini:/home/carla/CarlaUE4/Config/DefaultEngine.ini:ro'
      - '/tmp/.X11-unix/:/tmp/.X11-unix:rw'
      - '${XAUTHORITY}:/root/.Xauthority'
    environment:
      - DISPLAY=${DISPLAY}
      - USE_EXTERNAL_X=${DR_HOST_X}
      - XAUTHORITY=/root/.Xauthority
      - QT_X11_NO_MITSHM=1
      - TF_FORCE_GPU_ALLOW_GROWTH=True
    entrypoint: >
      /bin/bash ./CarlaUE4.sh -carla-rpc-port=2000 -quality-level=Low -nosound -carla-no-hud
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

    networks:
      - simnet

networks:
  simnet: #